# fly.toml app configuration file for onetime-docs
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'onetime-docs'
primary_region = 'ams'

[build]
dockerfile = 'Dockerfile'

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']
protocol = "tcp"
handlers = ["http"]

[[services.ports]]
handlers = ["http"]
port = 80
force_https = true

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1

[env]
