// app/app.config.ts

export default defineAppConfig({
  ui: {
    // Define primary and gray colors globally
    primary: "brand", // Your primary brand color
    gray: "midnight", // Your preferred shade of gray

    // Safelist specific colors to ensure they are generated by TailwindCSS,
    // especially if used dynamically.
    safelistColors: ["brand", "orange"],

    // Default icon configuration for light/dark modes
    icons: {
      light: "i-ph-moon-stars", // Icon for light mode toggle
      dark: "i-ph-sun", // Icon for dark mode toggle (Note: i-ph-moon is more common)
      dynamic: false,
    },

    // Global component configurations
    button: {
      // Default properties for all buttons
      default: {
        size: "md", // Default button size
        color: "gray", // Default button color variant
      },
      rounded: "rounded-md", // Default border radius for buttons
      // Define specific color variant styles if needed, e.g.:
      // color: {
      //   brand: { // Overrides for the 'brand' color variant
      //     solid: '...'
      //   }
      // }
    },

    input: {
      // Default properties for all inputs
      default: {
        size: "md", // Default input size
      },
      rounded: "rounded-md", // Default border radius for inputs (matches button)
    },

    card: {
      rounded: "rounded-xl", // Default border radius for cards
      // Default background and ring styles can also be set here
      // background: 'bg-white dark:bg-gray-900',
      // ring: 'ring-1 ring-gray-200 dark:ring-gray-800',
    },

    // Configuration specific to Nuxt UI Pro template components (if used)
    footer: {
      top: {
        wrapper: "border-t border-gray-200 dark:border-gray-800",
        container: "py-8 lg:py-16",
      },
      bottom: {
        wrapper: "border-t border-gray-200 dark:border-gray-800",
      },
    },

    page: {
      hero: {
        wrapper: "lg:py-24", // Adjust vertical padding for hero sections
      },
    },

    // Default font family - consider sans-serif for broader application UIs
    // font: {
    //   default: 'font-sans', // A more common default for web applications
    // },
    // Keep serif if it aligns with your specific blog design:
    font: {
      default: "font-serif",
    },
  },
});
